#! /bin/sh
# app servers
node /var/mtlfe/dispatch/lib/server.js -h mltfe.org -p 8001 >> /var/log/mtlfe/dispatch.log 2>&1 
node /var/mtlfe/dispatch/lib/server.js -h mltfe.org -p 8002 >> /var/log/mtlfe/dispatch.log 2>&1 
node /var/mtlfe/dispatch/lib/server.js -h mltfe.org -p 8003 >> /var/log/mtlfe/dispatch.log 2>&1 
# hook servers
node /var/mtlfe/dispatch/lib/hook.js -h mtlfe.org -p 9001 >> /var/log/mtlfe/dispatch.log 2>&1